language: ruby
cache: bundler

rvm:
  - 1.9.3
  - 2.0.0

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - morganshowman@gmail.com
    on_failure: change
    on_success: never
